config/routes.rb
MusicZone::Application.routes.draw do
  get "users/new"

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/whatshot',   to: 'static_pages#whatshot'
  match '/artists',   to: 'static_pages#artists'
  match '/albums',   to: 'static_pages#albums'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def whatshot
  end

  def about
  end

  def artists
  end

  def albums
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Music Zone Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.myspace.com/">Music Zone</a>
    by Wei Zhou
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Artists", artists_path %></li>
      <li><%= link_to "Albums", albums_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Music Zone", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "What is Hot",    whatshot_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://www.myspace.com/Help/AboutUS/">About my space </a>
  is a leading social entertainment destination.
  You can record and share your favorite or distasteful songs on Music Zone after
  visiting <a href="http://www.myspace.com/">myspace</a>. This
  is the sample application for Music Zone.
</p>

app/views/static_pages/albums.html.erb
<% provide(:title, 'Albums') %>
<h1>Albums</h1>
<p>
  Choose the hottest albums on
  <a href="http://www.myspace.com/music/albums">Albums page</a>.
</p>

app/views/static_pages/artists.html.erb
<% provide(:title, 'Artists') %>
<h1>Artists</h1>
<p>
  Choose your favorite artists on
  <a href="http://www.myspace.com/music/artists">Artists page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on accessing "myspace" website to record personal favorite song on Music Zone at the
  <a href="http://www.myspace.com/Help/">myspace help page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Music Zone</h1>

  <h2>
    This is the home page for the
    <a href="http://www.myspace.com/">Music Zone</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<!--%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %-->

app/views/static_pages/whatshot.html.erb
<% provide(:title, 'What is Hot') %>
<h1>What is Hot</h1>
<p>
  The <a href="http://www.myspace.com/">myspace</a>
  is a leading social entertainment destination powered by the passions of fans.
  Its content --<a href="http://www.myspace.com/whats-hot/">What's Hot</a> contains
  various kinds of news in so many fields, including music, celebrities, TV, movies, and games that
  you maybe interested in.
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>